# Generated by Django 5.1.3 on 2024-12-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('workout', '0007_userweighthistory_weighttracking_workoutresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workout.workoutprogram'),
        ),
    ]
