# Generated by Django 5.1.3 on 2024-11-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_exercise_options_alter_musclegroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='difficulty_level',
            field=models.CharField(choices=[('Легкая', 'Легкая'), ('Средняя', 'Средняя'), ('Сложная', 'Сложная')], default='Легкая', max_length=10, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='training_place',
            field=models.CharField(choices=[('Тренажерный зал', 'Тренажерный зал'), ('Дом', 'Дом')], default='Тренажерный зал', max_length=20, verbose_name='Место тренировки'),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='workout_type',
            field=models.CharField(choices=[('Кардио', 'Кардио'), ('Силовая', 'Силовая')], default='Кардио', max_length=10, verbose_name='Тип тренировки'),
        ),
    ]
