# Generated by Django 5.1.3 on 2024-12-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_workoutresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutResult',
        ),
    ]
