# Generated by Django 5.1.3 on 2024-12-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_alter_workoutresult_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttracking',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вес (кг)'),
        ),
    ]
