# Generated by Django 5.1.4 on 2024-12-12 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bench_press', 'Жим лежа'), ('squat', 'Приседание со штангой'), ('deadlift', 'Становая тяга')], max_length=20, verbose_name='Категория')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('video', models.URLField(verbose_name='Ссылка на видео')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рекорд',
                'verbose_name_plural': 'Рекорды',
                'ordering': ['-weight'],
            },
        ),
    ]
